### ISSUE TITLE
subspace issues

### ISSUE THREAD

**Issue by nirmalvarfa** [PixelMelt/Subspace#2]

**Comment by nirmalvarfa** [comment]
bro i m faceing a issues i cant install the mod then the game is not opening when subspace mod is actived 
its kepp on loading pls fix it bro pls 
thank u

**Comment by Pro-GamerX** [comment]
you need to download the tapemonkey and then inject the script

**Comment by Pro-GamerX** [comment]
than it will work

**Comment by PixelMelt** [comment]
insufficient information, join the discord for help

**Comment by nirmalvarfa** [comment]
Kk
